services:
  api:
    container_name: cc-backend-api
    restart: always
    build: 
      context: .
      target: development
    ports:
      - "${PORT:-3000}:${PORT:-3000}"  # Make port configurable via environment
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3000}
    volumes:  # Add volume mounts for development
      - .:/app
      - /app/node_modules  # Prevents overwriting container node_modules
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s  # Give the app time to start up
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - cc-network  # Add network for potential service communication

networks:
  cc-network:
    driver: bridge